//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thesis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;SyntaxDefinition name=&quot;C#&quot; extensions=&quot;.cs&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///	&lt;!-- The named colors &apos;Comment&apos; and &apos;String&apos; are used in SharpDevelop to detect if a line is inside a multiline string/comment --&gt;	
        ///	&lt;Color name=&quot;Comment&quot; foreground=&quot;#008000&quot; exampleText=&quot;// comment&quot; /&gt;
        ///	&lt;Color name=&quot;Class&quot; foreground=&quot;#2B91AF&quot; exampleText=&quot;class Test&quot; /&gt;
        ///	&lt;Color name=&quot;String&quot; foreground=&quot;#A31515&quot; exampleText=&quot;string text = &amp;quot;Hello, World!&amp;quot;&quot;/&gt;
        ///	&lt;Co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CSharpSyntaxHighlighting {
            get {
                return ResourceManager.GetString("CSharpSyntaxHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public static bool Equals(dynamic left, dynamic right)
        ///{
        ///
        ///}
        ///
        ///public struct EmptyCell
        ///{
        ///    public static dynamic operator +(dynamic a, EmptyCell b)
        ///    {
        ///        return a;
        ///    }
        ///
        ///    public static dynamic operator +(EmptyCell a, dynamic b)
        ///    {
        ///        return b;
        ///    }
        ///
        ///    public static dynamic operator +(EmptyCell a, EmptyCell b)
        ///    {
        ///        return a;
        ///    }
        ///
        ///    public static dynamic operator -(dynamic a, EmptyCell b)
        ///    {
        ///        return a;
        ///    }
        ///
        ///    public static dynamic op [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CSharpTestingBase {
            get {
                return ResourceManager.GetString("CSharpTestingBase", resourceCulture);
            }
        }
    }
}
